name: Node.js CI

on:
  push:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [22.x]
        template: [ cpp-github ] # https://github.com/vvvar/generator-cpp-github
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - shell: bash
      run: |
        npm install -g yo && \
        npm install -g yeoman-test && \
        npm install -g generator-${{ matrix.template }} && \
        yo --generators
        
    # && \
    # mkdir -pv my-app && \
    # cd my-app && \
    # yo ${{ matrix.template }}:app

    - uses: actions/github-script@v7.0.1
      with:
        script: |
          (async function () {
            const { helpers } = await import("yeoman-test");
            
            await helpers.run(                   // instantiates RunContext
                    '${{ matrix.template }}:app',             // namespace or generator
                    {},                      // test options
                    {}                       // environment options
                  )
                      .withAnswers({
                  ProjectName: "test-application",
                  ProjectNamePretty: "Test C++ Application",
                  ProjectDescription: "Dummy description for the application",
                  ProjectWebPage: "http://example.com",
                  ProjectMaintainersEmail: "tester@testerenko.com",
                });
          })();

    - shell: bash
      run: |
        ls -R
        
    # - shell: cmd
    #   run: |
    #     cd  &&^
    #     7z a -tzip "my-vue-app-${{ matrix.node-version }}.zip" &&^
    #     dir
        
    - uses: actions/upload-artifact@v4.6.0
      with:
        name: "${{ matrix.template }}-${{ matrix.node-version }}.zip"
        path: "${{ matrix.template }}"
