name: Node.js CI

on:
  push:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [24.x]
        template:
        - {
            name: "cpp-github",
            answer:
              ProjectName: "test-application",
              ProjectNamePretty: "Test C++ Application",
              ProjectDescription: "Dummy description for the application",
              ProjectWebPage: "http://example.com",
              ProjectMaintainersEmail: "tester@testerenko.com"
          }
        # https://github.com/vvvar/generator-cpp-github
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - shell: bash
      run: |
        cat << EOF > prompt-answer.json
        ${{ toJSON(matrix.template.answer) }}
        EOF
      
    - shell: bash
      run: |
        npm i && \
        npm install -g yo && \
        npm install -g yeoman-test && \
        npm install -g generator-${{ matrix.template }} && \
        yo --generators && \
        node .
        
    - uses: actions/upload-artifact@v4.6.0
      with:
        name: "${{ matrix.template }}-${{ matrix.node-version }}.zip"
        path: "dist"
